backend: tensorflow
class_name: Sequential
config:
  layers:
  - class_name: Conv2D
    config:
      activation: relu
      activity_regularizer: null
      batch_input_shape: !!python/tuple
      - null
      - 32
      - 32
      - 3
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config:
          dtype: float32
      bias_regularizer: null
      data_format: channels_last
      dilation_rate: &id001 !!python/tuple
      - 1
      - 1
      dtype: float32
      filters: 64
      kernel_constraint: null
      kernel_initializer:
        class_name: GlorotUniform
        config:
          dtype: float32
          seed: null
      kernel_regularizer: null
      kernel_size: !!python/tuple
      - 5
      - 5
      name: conv2d
      padding: same
      strides: *id001
      trainable: true
      use_bias: true
  - class_name: MaxPooling2D
    config:
      data_format: channels_last
      dtype: float32
      name: max_pooling2d
      padding: valid
      pool_size: &id002 !!python/tuple
      - 4
      - 4
      strides: *id002
      trainable: true
  - class_name: Conv2D
    config:
      activation: relu
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config:
          dtype: float32
      bias_regularizer: null
      data_format: channels_last
      dilation_rate: *id001
      dtype: float32
      filters: 32
      kernel_constraint: null
      kernel_initializer:
        class_name: GlorotUniform
        config:
          dtype: float32
          seed: null
      kernel_regularizer: null
      kernel_size: !!python/tuple
      - 5
      - 5
      name: conv2d_1
      padding: same
      strides: *id001
      trainable: true
      use_bias: true
  - class_name: MaxPooling2D
    config:
      data_format: channels_last
      dtype: float32
      name: max_pooling2d_1
      padding: valid
      pool_size: &id003 !!python/tuple
      - 4
      - 4
      strides: *id003
      trainable: true
  - class_name: Conv2D
    config:
      activation: relu
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config:
          dtype: float32
      bias_regularizer: null
      data_format: channels_last
      dilation_rate: *id001
      dtype: float32
      filters: 32
      kernel_constraint: null
      kernel_initializer:
        class_name: GlorotUniform
        config:
          dtype: float32
          seed: null
      kernel_regularizer: null
      kernel_size: !!python/tuple
      - 3
      - 3
      name: conv2d_2
      padding: same
      strides: *id001
      trainable: true
      use_bias: true
  - class_name: MaxPooling2D
    config:
      data_format: channels_last
      dtype: float32
      name: max_pooling2d_2
      padding: valid
      pool_size: &id004 !!python/tuple
      - 2
      - 2
      strides: *id004
      trainable: true
  - class_name: Flatten
    config:
      data_format: channels_last
      dtype: float32
      name: flatten
      trainable: true
  - class_name: Dense
    config:
      activation: relu
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config:
          dtype: float32
      bias_regularizer: null
      dtype: float32
      kernel_constraint: null
      kernel_initializer:
        class_name: GlorotUniform
        config:
          dtype: float32
          seed: null
      kernel_regularizer: null
      name: dense
      trainable: true
      units: 128
      use_bias: true
  - class_name: Dense
    config:
      activation: linear
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config:
          dtype: float32
      bias_regularizer: null
      dtype: float32
      kernel_constraint: null
      kernel_initializer:
        class_name: GlorotUniform
        config:
          dtype: float32
          seed: null
      kernel_regularizer: null
      name: dense_1
      trainable: true
      units: 32
      use_bias: true
  - class_name: Dense
    config:
      activation: linear
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config:
          dtype: float32
      bias_regularizer: null
      dtype: float32
      kernel_constraint: null
      kernel_initializer:
        class_name: GlorotUniform
        config:
          dtype: float32
          seed: null
      kernel_regularizer: null
      name: dense_2
      trainable: true
      units: 3
      use_bias: true
  name: sequential
keras_version: 2.2.4-tf
